config/routes.rb
Rails.application.routes.draw do
  # get 'diagnoses_lists/index'
  # get 'diagnoses_lists/show'

  resources :templates
  resources :queries
  
  resources :ehrs do
#    resources :compositions
    resources :monshinsb
    resources :diagnoses
    resources :diagnoses_lists
#    get 'search' => 'diagnoses#search'
  end

  root 'ehrs#index'
end

app/models/query.rb
require 'json'

class Query
  include ActiveModel::Model
  include ActiveModel::Attributes
  include Base

  class << self
    def get(aql)
      response = Base.ehrbase_connection.get('query/aql', query: {'q' => aql })
      JSON.parse response.body
    end
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    @results = Query.get(queries_params[:aql])
  end

  protected

  def queries_params
    params.permit(:aql) #(:id, :ehr_id, :system, :version, :
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/index.html.erb
<h1>Query</h1>

<%= form_with url: queries_path, method: :get, local: true do |form| %>
<%= form.text_area :aql %>
<%= form.submit '検索' %>
<% end %>

<% if @results['error'] %>
<%= @results %>
<% else %>
<table class="table">
  <thead>
    <tr>
      <% @results['columns'].each do |column| %>
      <th><%= column['name'] %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @results['rows'].each do |row| %>
    <tr>
      <% row.each do |item| %>
      <td><%= item %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>