config/routes.rb
Rails.application.routes.draw do
  # get 'diagnoses_lists/index'
  # get 'diagnoses_lists/show'

  resources :templates
  resources :queries
  
  resources :ehrs do
#    resources :compositions
    resources :monshinsb
    resources :diagnoses
    resources :diagnoses_lists
#    get 'search' => 'diagnoses#search'
  end

  root 'ehrs#index'
end

app/models/ehr.rb
class Ehr
  include ActiveModel::Model
  include ActiveModel::Attributes
  include Base

  attr_reader :id
  attr_reader :errors

  attribute :id, :string
  
  define_model_callbacks :save, only: :before
  before_save { throw(:abort) if invalid? }

  def initialize(params = {})
    @id = params[:id]
    @errors = ActiveModel::Errors.new(self)
  end

  def save
    unless @id
      res = Base.connection.post('ehr')
      @id = res.headers['ETag'][1..-2]
    end
  end

  def save!
    save
    self
  end

  def compositions
    Compositions.find_all(ehr_id: self.id)
  end

  def person
    Person.find_by(ehr_id: self.id)
  end

  class << self
    def create!(params = {})
      Ehr.new(params).save!
    end

    def all
      Person.all.map do |person|
        Ehr.new(id: person.ehr_id)
      end
    end
    
    def find(id)
      Ehr.new(id: id)
    end
  end
end

app/controllers/ehrs_controller.rb
class EhrsController < ApplicationController
  def index
    @ehrs = Ehr.all
  end

  def show
    @ehr = Ehr.find(params[:id])
  end

  def new
    @ehr = Ehr.new
  end
end

app/views/ehrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>EHRs</h1>

<table>
  <thead>
    <tr>
      <th>EHR ID</th>
      <th>ORCA ID</th>
      <th>氏名</th>
      <th>生年月日</th>
      <th>性別</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ehrs.each do |ehr| %>
      <tr>
        <td><%= ehr.id %></td>
	<td><%= ehr.person.orca_id %></td>
        <td><%= ehr.person.name %></td>
	<td><%= ehr.person.dob %></td>
	<td><%= ehr.person.gender %></td>
        <td><%= link_to 'Show', ehr_diagnoses_lists_path(ehr.id) %></td>
        <td><%= link_to 'Edit', edit_ehr_path(ehr.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />